### ISSUE TITLE
Link down

### ISSUE THREAD

**Issue by ariidesu** [fadilfadz01/Astoria-on-L950s#1]
The link for Astoria FFU seems to be down. Can you give a new link?

**Comment by egor835** [comment]
I saved this file on my hdd, here is the link: https://drive.google.com/file/d/1PL0AesZ-F0au3_UHsCy2nOYQyR6mS601/view?usp=share_link

**Comment by VLPLELEVEN** [comment]
I've been trying for some time, but on my 950, it's only giving the error Signature check of FFU file fails. Reason(s): The FFU file is not correctly signed or not signed for this device.
